name: "Autosend"

on:
  push:
    branches: main
  schedule:
    - cron: '25 09 * * *' # 每天9点25分自动执行
  workflow_dispatch:
    inputs:

jobs:
  autosend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Build Docker Image
        run: |
          docker build -t my-groupme-notify-action .

      - name: Run GroupMe Notification
        run: |
          docker run --rm \
            -e GM_BOT_ID=${{ secrets.GM_BOT_ID }} \
            -e GM_API_KEY=${{ secrets.GM_API_KEY }} \
            my-groupme-notify-action

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 2
          keep_minimum_runs: 6
